/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Cleveland Museum of Art (https://sketchfab.com/clevelandart)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/1930331-nataraja-shiva-as-the-lord-of-dance-6862a3c673d4434a8dc39ced2a5b5720
Title: 1930.331 Nataraja, Shiva as the Lord of Dance
*/

import { useGLTF } from "@react-three/drei";

export default function Model1(props) {
  const { nodes, materials } = useGLTF("./models/hero/scene.glb");

  return (
    <group scale={2} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Nataraja_Mat}
        position={[0.017, -1.569, 1.491]}
        rotation={[-Math.PI, 0.42, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/hero/scene.glb");
